/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java */

#ifndef _Included_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java
#define _Included_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java
 * Method:    initSensor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_1pm1001_1java_initSensor
  (JNIEnv *, jobject, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java
 * Method:    getDustValue
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_1pm1001_1java_getDustValue
  (JNIEnv *, jobject);

/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java
 * Method:    freeSensor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_1pm1001_1java_freeSensor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
