/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001 */

#ifndef _Included_MinT_ExternalDevice_Sensing_Dust_MinTDriver_pm1001
#define _Included_MinT_ExternalDevice_Sensing_Dust_MinTDriver_pm1001
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java
 * Method:    initSensor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MinT_ExternalDevice_Sensing_Dust_MinTDriver_1pm1001_initSensor
  (JNIEnv *, jobject);

/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java
 * Method:    getDustData
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_MinT_ExternalDevice_Sensing_Dust_MinTDriver_1pm1001_getDustData
  (JNIEnv *, jobject);

/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_pm1001_java
 * Method:    freeSensor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MinT_ExternalDevice_Sensing_Dust_MinTDriver_1pm1001_freeSensor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
