/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java */

#ifndef _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
#define _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    initSensor_PWM
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_initSensor_1PWM
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    initSensor_GPIO
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_initSensor_1GPIO
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    freeSensor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_freeSensor
  (JNIEnv *, jobject);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    delay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_delay
  (JNIEnv *, jobject, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    set_pwmRGB
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_set_1pwmRGB
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    color_PWM
 * Signature: (IIDDD)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_color_1PWM
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    color_RGB_PWM
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_color_1RGB_1PWM
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    pin_low
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_pin_1low
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    pin_high
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_pin_1high
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java
 * Method:    uSleep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_1RGB_1LED_1java_uSleep
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController */

#ifndef _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController
#define _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController
#ifdef __cplusplus
extern "C" {
#endif
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController_MIN_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController_MIN_PRIORITY 1L
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController_NORM_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController_NORM_PRIORITY 5L
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController_MAX_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_BlueController_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController */

#ifndef _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController
#define _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController
#ifdef __cplusplus
extern "C" {
#endif
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController_MIN_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController_MIN_PRIORITY 1L
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController_NORM_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController_NORM_PRIORITY 5L
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController_MAX_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_GreenController_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController */

#ifndef _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController
#define _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController
#ifdef __cplusplus
extern "C" {
#endif
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController_MIN_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController_MIN_PRIORITY 1L
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController_NORM_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController_NORM_PRIORITY 5L
#undef MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController_MAX_PRIORITY
#define MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_RedController_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_ColorDelay */

#ifndef _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_ColorDelay
#define _Included_MinTFramework_ExternalDevice_Control_RGBLED_MinTDriver_RGB_LED_java_ColorDelay
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
