/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_cm1101_java */

#ifndef _Included_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_cm1101_java
#define _Included_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_cm1101_java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_cm1101_java
 * Method:    initSensor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_1cm1101_1java_initSensor
  (JNIEnv *, jobject, jint);

/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_cm1101_java
 * Method:    freeSensro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_1cm1101_1java_freeSensro
  (JNIEnv *, jobject);

/*
 * Class:     MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_cm1101_java
 * Method:    getCO2Value
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MinTFramework_ExternalDevice_Sensing_Dust_MinTDriver_1cm1101_1java_getCO2Value
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
